<a href="https://colab.research.google.com/github/Harsh-C7/Sonar-Rock-vs-Mine-prediction-project/blob/main/TensorflowTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Harsh!!")

Hello Harsh!!


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
vertor = tf.Variable([[1,2,3], [4, 5, 6]])
vertor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
import numpy as np

array = np.array([[1,2,3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tensor = tf.convert_to_tensor(array)
tensor

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation